#!/bin/sh

set -e

case "$1" in
	install|upgrade)
		dpkg-divert --package pocketchip-configs --add --rename \
			--divert /etc/skel/.config/Thunar/cc.accels.scm \
			/etc/skel/.config/Thunar/accels.scm
		dpkg-divert --package pocketchip-configs --add --rename \
			--divert /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/cc.thunar.xml \
			/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml
	;;
esac
